### PR TITLE
RFC for Zuul v3 integration with Windows CI

### PR DESCRIPTION
**Pull request by kaweue**

### CODE REVIEW

**Review by jablonskim — APPROVED** [review]

**Review by sodar — APPROVED** [review]
Looks good to me.

**Comment by jluk-codi** [comment]
I would add the inability to do proper gate testing using two CI systems as a "drawback" - Windows jobs cannot be voting in the gate pipeline when they are executed by a different Zuul instance.

Also, add some information about other approaches (unsuitable or WIP right now) for comparison and/or future planning:
Zuul v3 direct Windows support: https://review.openstack.org/#/q/topic:windows-support
Zuul v3 direct Jenkins support http://lists.zuul-ci.org/pipermail/zuul-discuss/2018-March/000056.html

Cheers,
Jarek

**Review by m-kostrzewa — CHANGES_REQUESTED** [review]
I've got concerns about the nature of cooperation between Windows and Devops teams in relation to infra and code ownership.

How I see it, it can go two ways:
1. Both teams share parts of the codebase responsible for the integration. In this case, this must be equal ownership.
2. One team is "server" and another is "client". "Server" client is responsible for providing the functionality. "Client" team is reponsible for delivering tests that run on changes introduced by "server" team.

(1). could be achieved by structuring code and components into something akin to "shared kernel" pattern from DDD:

>However a Shared Kernel will only work if all of the development teams work to share and communicate the requirements of the shared code. This means that the design of the Shared Kernel can’t evolve as quickly as other aspects of the application, and any changes must be agreed upon by members of each development team.

> Each development team will also have to take equal responsibility for maintaining unit tests that ensure the functionality of the Shared Kernel remains consistent.

> When there is a shared requirement of a certain aspect of the application, and relatively high levels of communication and low levels of political unrest, the Shared Kernel integration strategy can be easier to implement than many of the other integration strategies we will look at in this article.

(2) could be achieved using something like "Customer/Supplier" pattern:

> This relationship can play out in a number of different ways.

> Firstly the downstream team can be at the mercy of the upstream team if the upstream team make changes without thinking about the requirements of the downstream team.

> Alternatively the upstream team can feel restricted on the design and implementation of their application if the downstream team has control over how their application evolves.

> The downstream team is dependent on the upstream team, but the upstream team is not responsible for the deliverables of the downstream team. In order to make this situation work, the two teams need to have a formal relationship where the requirements of the downstream team are considered, as would occur in any Customer / Supplier relationship.

> This means future development priorities, tasks and requests need to be agreed upon by members of both teams.

> Both teams should also agree upon a series of Acceptance tests that will ensure the interface of the boundary remains consistent. This means the upstream team can evolve their application as long as the interface remains consistent, and the downstream team can be assured that they won’t wake up one day to find their application broken because of the upstream team’s changes.

> The Customer / Supplier relationship works best when both teams’ goals are aligned or they both report to the same layer of management. When the goals of the two teams are not aligned, the relationship will often break down.

(excerpts from http://www.culttt.com/2014/11/26/strategies-integrating-bounded-contexts/)

**It is crucial that both teams agree on further cooperation style, and we get a go-ahead from mgmt**

Depending on which route we decide to go for, this RFC lacks information like:

* Where is the config for zuulv3 to launch the Nodepool VM mentioned in the RFC? 
* Where are the credentials for maintaining this integration? (e.g. maybe when Windows team needs to reload Zuulv3 config?)
* Where are the relevant ansible playbooks and zuul tentacle code? Separate repository(/ies)? contrail-project-config? contrail-windows-ci?
* What if there are infra problems with Nodepool VMs? Does Windows team need access and knowledge on Juniper Openstack?
* Can we implement this RFC in a way that doesn't require Windows team to have access to infra?
* etc

**Comment by m-kostrzewa** [comment]
If we go the "shared kernel" route, it would probably consist of just nodepool config and zuul job.

**Comment by diabelko** [comment]
My thoughts:

- There should be a very clear demarcation line of responsibilities regarding the maintenance of both CIs. Our team is physically incapable of handling issues on Windows CI due to lack of time, knowledge and even access rights - I believe it is the case for you guys as well.
- If there's a shared code and both CIs require it to run and both CIs vote - both parties should be responsible for the code equally.
- Common code should be completely separate from the rest of the code.
- Only one system can do gating and currently it is ours. In our scenario it is impossible to treat both CIs as equals. It is impossible to make sure code will not break Windows CI during merge time.
- How to perform code review efficiently if a half of the reviewers is not familiar with one half of the system it'll run on?
- If a change passed the tests of the both teams, got merged and suddenly it breaks one of the CIs, how to approach it? Do we force merge the change? What if it'll break the other CI? What is the priority?
- How does one team's schedule affect the changes needed by the other team (e.g. help needed to fix failures in Zuulv3)?

**Comment by m-kostrzewa** [comment]
Closing this until this topics is brought back again. @PawelMarchewkaCodiLime @jacek-izykowski

**Comment by m-kostrzewa** [comment]
Hi all, I'm merging for posterity.

**Pull request merged**
